{
    'name': 'Revive Application',
    'version': '1.1',
    'category': 'Tools',
    'summary': 'Manage Membership, Partnerships, Volunteers, Donations, Events, Media Streaming and Broadcasting, store and more ministerials module.',
    'description': 'Module to manage volunteers and donors, track events, and handle various church-related activities.',
    'author': 'Christian Revive',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'sale', 'product', 'contacts', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/broadcast.xml',
        'views/book.xml',
        'views/daily_wisdom.xml',
        'views/notification.xml',
        'views/medical_codes.xml',
        'views/health.xml',
        'views/daily_verse.xml',
        'views/partner_ministry.xml',
        'data/sequence.xml',
        'views/music.xml',
        'views/project.xml',
        'views/prayer_request.xml',
        'views/event.xml',
        'views/thought_of_the_day.xml',
        'views/profile_fields.xml',
        'views/store.xml',
        'views/sabbath_school.xml',
        'views/patients.xml',
        'views/staff.xml',
        'views/volunteers.xml',
        'views/daily_devotional.xml',
        'views/client_detail.xml',
        'views/members.xml',
        'views/donate.xml',
        'views/volunteers_skills.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}